services:
  dumbterm:
    # image: dumbwareio/dumbterm:latest
    build: .
    container_name: dumbterm
    restart: unless-stopped
    ports:
      - ${DUMBTERM_PORT:-3000}:3000
    volumes:
      - ${DUMBTERM_CONFIG:-./config/starship.toml}:/root/.config/starship.toml
    environment:
      # The title shown in the web interface
      SITE_TITLE: ${DUMBTERM_SITE_TITLE:-My Terminal}
      # Optional PIN protection (leave empty to disable)
      DUMBTERM_PIN: ${DUMBTERM_PIN:-}
      # The base URL for the application
      BASE_URL: ${DUMBTERM_BASE_URL:-http://localhost:3000} # Use ALLOWED_ORIGINS below to restrict cors to specific origins
      ENABLE_STARSHIP: ${ENABLE_STARSHIP:-false}
      # (OPTIONAL)
      # Usage: Comma-separated list of urls: http://localhost:port,http://internalip:port,https://base.proxy.tld,https://authprovider.domain.tld
      # ALLOWED_ORIGINS: ${DUMBTERM_ALLOWED_ORIGINS:-http://localhost:3000} # Comment out to allow all origins (*)