# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Add a blank line between shell prompts
add_newline = true

# Replace the "❯" symbol in the prompt with "➜"
[character]
success_symbol = "[➜](bold green)"
error_symbol = "[➜](bold red)"

# Show current directory
[directory]
truncation_length = 8
truncate_to_repo = true

# Git configuration
[git_branch]
symbol = " "
truncation_length = 20
truncation_symbol = ""

[git_status]
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"

# Show execution time
[cmd_duration]
min_time = 500
format = "took [$duration](bold yellow)"