name: Build and Push Docker Image

on:
  push:
    branches:
      - main # Trigger the workflow on pushes to the main branch

env:
  DOCKER_IMAGE: dumbwareio/dumbterm
  PLATFORMS: linux/amd64,linux/arm64

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set Docker tags
        id: docker_meta
        run: |
          TAGS="${{ env.DOCKER_IMAGE }}:${{ github.sha }}"
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            TAGS+=" ${{ env.DOCKER_IMAGE }}:latest"
          elif [ "${{ github.ref }}" = "refs/heads/testing" ]; then
            TAGS+=" ${{ env.DOCKER_IMAGE }}:testing"
          fi
          echo "DOCKER_TAGS=$TAGS" >> $GITHUB_ENV

      - name: Build and Push Multi-Platform Image
        run: |
          docker buildx create --use
          docker buildx build --platform ${{ env.PLATFORMS }} \
            --tag ${{ env.DOCKER_IMAGE }}:${{ github.sha }} \
            --tag ${{ env.DOCKER_IMAGE }}:latest \
            --push .

      - name: Update Docker Hub Description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ env.DOCKER_IMAGE }}
          short-description: "A stupidly simple web-based terminal emulator, with common tools and Starship enabled (via Docker)! 🚀"
          readme-filepath: ./README.md